apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-data
  namespace: minecraft
  labels:
    app: mc-ftba
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
