apiVersion: v1
kind: Service
metadata:
  name: minecraft-svc
  namespace: minecraft
spec:
  type: LoadBalancer
  selector:
    app: minecraft
  ports:
    - port: 80
      targetPort: 25565
      name: http
  clusterIP: 
