apiVersion: v1
kind: Service
metadata:
  name: minecraft-svc
  namespace: minecraft
  annotations:
    external-dns.alpha.kubernetes.io/hostname: shazzserver.devops.hg-prototypes.com
spec:
  type: LoadBalancer
  selector:
    app: minecraft
  ports:
    - port: 80
      targetPort: 25565
      name: http
  clusterIP: 172.20.33.165
