---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: minecraft
  name: minecraft
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: minecraft
spec:
  type: LoadBalancer
  ports:
  - name: minecraft
    port: 25565
    targetPort: minecraft
    protocol: TCP
  selector:
    app: minecraft

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: minecraft
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: minecraft
        image: itzg/minecraft-server:multiarch
        imagePullPolicy: Always
        resources:
          requests:
            memory: 12000Mi
            cpu: 6000m
        startupProbe:
          tcpSocket:
            port: 25565
          failureThreshold: 10
          periodSeconds: 500
        readinessProbe:
          tcpSocket:
            port: 25565
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          tcpSocket:
            port: 25565
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 10
          successThreshold: 1
          timeoutSeconds: 1
        env:
        - name: EULA
          value: "TRUE"
        - name: TYPE
          value: "FTBA"
        - name: FTB_MODPACK_ID
          value: "79"
        - name: FTB_LEGACYJAVAFIXER
          value: "FALSE"
        - name: VERSION
          value: "1.16.4"
        - name: DIFFICULTY
          value: "hard"
        - name: WHITELIST
          value: ""
        - name: OPS
          value: "shazzberry"
        - name: ICON
          value: ""
        - name: MAX_PLAYERS
          value: "20"
        - name: MAX_WORLD_SIZE
          value: "10000"
        - name: ALLOW_NETHER
          value: "TRUE"
        - name: ANNOUNCE_PLAYER_ACHIEVEMENTS
          value: "TRUE"
        - name: ENABLE_COMMAND_BLOCK
          value: "TRUE"
        - name: FORCE_GAMEMODE
          value: "FALSE"
        - name: FORCE_REDOWNLOAD
          value: "FALSE"
        - name: GENERATE_STRUCTURES
          value: "TRUE"
        - name: HARDCORE
          value: "FALSE"
        - name: MAX_BUILD_HEIGHT
          value: "256"
        - name: MAX_TICK_TIME
          value: "60000"
        - name: SPAWN_ANIMALS
          value: "TRUE"
        - name: SPAWN_MONSTERS
          value: "TRUE"
        - name: SPAWN_NPCS
          value: "TRUE"
        - name: VIEW_DISTANCE
          value: "10"
        - name: SEED
          value: ""
        - name: MODE
          value: "survival"
        - name: MOTD
          value: "Welcome to Minecraft on Kubernetes by Shazzberry!"
        - name: PVP
          value: "TRUE"
        - name: LEVEL_TYPE
          value: "DEFAULT"
        - name: GENERATOR_SETTINGS
          value: ""
        - name: LEVEL
          value: ""
        - name: WORLD
          value: ""
        - name: MODPACK
          value: ""
        - name: REMOVE_OLD_MODS
          value: "FALSE"
        - name: ONLINE_MODE
          value: "TRUE"
        - name: MEMORY
          value: "12000M"
        - name: JVM_OPTS
          value: "-Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true"
        - name: JVM_XX_OPTS
          value: "-Xms10G -Xmx10G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1"


        ports:
        - name: minecraft
          containerPort: 25565
          protocol: TCP

        volumeMounts:
        - name: datadir
          mountPath: /data

      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: minecraft-datadir
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-datadir
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

